PREFIX schema: <http://schema.org/>

CONSTRUCT {
    ?recipe a schema:Recipe ;
            schema:name ?e ;
            
            schema:prepTime ?f ;
            schema:cookTime ?b ;
            schema:totalTime ?h ;

            schema:recipeInstructions ?c ;

            schema:aggregateRating [ a schema:AggregateRating ;
                schema:ratingValue ?g ] ;

            schema:nutrition [ a schema:NutritionInformation ;
                schema:calories [ a schema:Energy ;
                    schema:name ?a ] ;
                ] ;
}

WHERE {
    BIND(IRI(?i) AS ?recipe)
}
