PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

###########################################
# construct general recipe info           #
###########################################

CONSTRUCT {
    ?recipe a schema:Recipe ;
            schema:name ?e ;
            
            schema:prepTime ?f ;
            schema:cookTime ?b ;
            schema:totalTime ?h ;

            schema:recipeInstructions ?c ;

            schema:aggregateRating [ a schema:AggregateRating ;
                schema:ratingValue ?ratings ] ;

            schema:nutrition [ a schema:NutritionInformation ;
                schema:calories [ a schema:Energy ;
                    schema:name ?energy ] ;
                ] ;            
}

WHERE {
    BIND(IRI(?i) AS ?recipe) .
    BIND(STRDT(?a, xsd:integer) as ?energy) .
    BIND(STRDT(?g, xsd:decimal) as ?ratings) .
}

OFFSET 1

###########################################
# construct recipe ingredients            #
###########################################

CONSTRUCT {
   ?recipe schema:recipeIngredient ?ingredient ;
}

WHERE {
    BIND(IRI(?i) AS ?recipe) .

    ?ingredients apf:strSplit (?d ",")
    BIND(?ingredients as ?ingredient)                                                                                                                                                                                                    
    filter(BOUND(?d))
}

OFFSET 1
