# Ask if there are some recipes that can be prepared in total time of 1-3 minutes.

PREFIX schema: <http://schema.org/>
PREFIX minutes: <http://www.w3.org/TR/owl-time/#time:minutes>

ASK {
	?recipe a schema:Recipe .
		
	OPTIONAL {
		?recipe schema:prepTime ?prepTime .
		?prepTime minutes: ?prepTimeMinutes .
	} .
	OPTIONAL {
		?recipe schema:cookTime ?cookTime .
		?cookTime minutes: ?cookTimeMinutes .
	} .
	OPTIONAL {
		?recipe schema:totalTime ?totalTime .
		?totalTime minutes: ?totalTimeMinutes .
	} .

	BIND(IF(BOUND(?prepTimeMinutes), ?prepTimeMinutes, 0) AS ?prepTimeValue) .
	BIND(IF(BOUND(?cookTimeMinutes), ?cookTimeMinutes, 0) AS ?cookTimeValue) .
	BIND(IF(BOUND(?totalTimeMinutes), ?totalTimeMinutes, ?prepTimeValue + ?cookTimeValue) AS ?totalTimeValue) .

	FILTER(?totalTimeValue > 0 && ?totalTimeValue < 4)
}