# Match ingredient entities with descriptions from dbpedia.

PREFIX ex: <http://example.org/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
	?ingredient rdfs:comment ?comment .
}
WHERE {
	?ingredient a ex:Ingredient .
	?ingredient owl:sameAs ?sameIngredient .

	BIND(URI(STR(?sameIngredient)) as ?ingr) .

	SERVICE <http://dbpedia.org/sparql> {
			?ingr rdfs:comment ?comment .
		}

	FILTER (CONTAINS(STR(?sameIngredient), "dbpedia"))
	FILTER (LANG(?comment) = "en")
}