PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

###########################################
# construct general recipe info           #
###########################################

CONSTRUCT {
    ?recipe a schema:Recipe ;
            schema:name ?recipeName ;
            
            schema:totalTime ?totalTime ;
            schema:keywords ?tags ;
            schema:description ?description ;

            schema:recipeInstructions ?steps ;

            schema:author [ a schema:Person ;
                schema:identifier ?contributor_id ] ;  

            schema:datePublished ?date ;

            schema:nutrition [ a schema:NutritionInformation ;
                schema:name ?nutrition ] ; 
}

WHERE {
    BIND(IRI(CONCAT("https://www.food.com/recipe/", ?id)) AS ?recipe) .
    BIND(REPLACE(?name, "[ ]+", " ") as ?recipeName)
    BIND(STRDT(?submitted, schema:DateTime) as ?date) .
    BIND(STRDT(?minutes, xsd:integer) as ?totalTime) .
}

###########################################
# construct recipe ingredients            #
###########################################

CONSTRUCT {
   ?recipe schema:recipeIngredient ?ingredient ;
}

WHERE {
    BIND(IRI(CONCAT("https://www.food.com/recipe/", ?id)) AS ?recipe) .

    BIND(STRDT(?ingredients, xsd:string) as ?ingr_literal) .
    BIND(REPLACE(?ingr_literal, "[\\[\\]']", "") as ?ingr)

    ?ingr_list apf:strSplit (?ingr ",")
    BIND(?ingr_list as ?ingredient)                                                                                                                                                                                                    
    filter(BOUND(?ingredients))
}
